# Generated by Django 3.0.8 on 2020-07-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbibli', '0002_auto_20200713_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='borrowername',
            new_name='borrowerext',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_date',
            new_name='checkout_date',
        ),
    ]
