# Generated by Django 2.2.7 on 2019-12-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='abstract',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='localisation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_volume',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='serie_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
