# Generated by Django 2.2.7 on 2020-01-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibli', '0003_loan_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
